# Instructions:
# 1)set the values you want
# 2) run galgo/create_params_and_runJobs
# 3) commit & push. your experiments will be automatically run in Galgo
# 4) when the whole array of jobs is finished, outputs/ folder will be pushed to repository
# 5) pull in local to get the outputs update
#
estimator:
     - "src.estimators.naivebayes.NaiveBayes"
#    - "src.estimators.AODE.A1DE"

validation:
    - "HOLD"
#    - "CV"

m: 1  #for mxn CV. ignored if validation=HOLD
n: 10 #for mxn CV, or train_test split validation n times
t: 0.33 # range (0-1), %data used for test. ignored if validation="CV"
seed: 0
stratify: true
discretize: false

file:
  nominal:
 #    - car
 #    - contact-lenses
 #    - hayes-roth
 #    - lung-cancer
 #    - postoperative-patient-data
 #    - splice
 #    - chess
 #    - housevotes
 #    - mushroom
 #    - primary-tumor
 #    - tic-tac-toe
 #    - chess_toy
 #    - kr-vs-kp
 #    - nursery
 #    - promoters
 #    - zoo
 #    - poker-hand

  numeric:
     - balance-scale
     - ecoli_toy
     - iris
     - pageblocks
     - sonar
     - vehicle
     - breast-w
     - glass
     - heart-statlog
     - letter
     - spambase
     - waveform-5000
     - ecoli
     - ionosphere
     - optdigits
     - segment
     - wine

  mix:
      - census-income
      - localization
      - contrareceptive-mc
      - cylinder-bands
      - german
      - vowel
      - autos
      - credit-a
      - dermatology
      - hepatitis
      - hypothyroid
      - lymph
      - teacher-ae
      - weather




