#!/bin/sh 
 #PBS -N agemoea 
 #PBS -l mem=2500mb 
 #PBS -J 1-12 

export PATH=/home/pbermejo/.local/lib/python3.8/site-packages:$PATH
export PYTHONPATH=/home/pbermejo/.local/lib/python3.8/site-packages:$PYTHONPATH
alias python=/usr/local/bin/python3.8
cd /home/pbermejo/MONRP


home="/home/pbermejo/"
paramFile=$home"/MONRP/galgo/pablo/params_file"

linea=`awk -v line=$PBS_ARRAY_INDEX 'NR==line {print $0}' $paramFile`
col=0


python /home/pbermejo/MONRP/executer_driver.py -c "$linea"
