#!/bin/bash
# execute galgo.sh from project directory
# project directory files: galgo.sh, execute.sh, galgo/configurations.py, configs.txt (autogenerated)
source ../newvenv/bin/activate

NAME="monrp-backtracking"

qsub -N "$NAME" \
     -e "$PWD"/errors/ \
     -o "$PWD"/outputs/ \
     -v CWD="$PWD" "$PWD"/execute_backtracking.sh