from galgo.grasp.configurations_grasp import generate_configurations


def generate_configurations_paretos():
    # grasp grasp 1 5 10 10 best_first_neighbor
    # opciones------------------------------------------------------------------
    f = open("configs_pareto.txt", "w")

    algorithms = [
        "grasp grasp 1 5 300 100 uniform None None",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_random None",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_sorted_score None",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_sorted_score_r None",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_random_domination None",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_sorted_domination None",
        "grasp grasp 1 5 300 100 uniform None after_local",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_random after_local",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_sorted_score after_local",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_sorted_score_r after_local",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_random_domination after_local",
        "grasp grasp 1 5 300 100 uniform best_first_neighbor_sorted_domination after_local",

        "grasp grasp 1 5 300 100 stochastically None None",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_random None",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_sorted_score None",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_sorted_score_r None",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_random_domination None",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_sorted_domination None",
        "grasp grasp 1 5 300 100 stochastically None after_local",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_random after_local",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_sorted_score after_local",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_sorted_score_r after_local",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_random_domination after_local",
        "grasp grasp 1 5 300 100 stochastically best_first_neighbor_sorted_domination after_local",

        "grasp grasp 2 5 300 100 uniform None None",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_random None",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_sorted_score None",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_sorted_score_r None",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_random_domination None",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_sorted_domination None",
        "grasp grasp 2 5 300 100 uniform None after_local",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_random after_local",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_sorted_score after_local",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_sorted_score_r after_local",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_random_domination after_local",
        "grasp grasp 2 5 300 100 uniform best_first_neighbor_sorted_domination after_local",

        "grasp grasp 2 5 300 100 stochastically None None",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_random None",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_sorted_score None",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_sorted_score_r None",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_random_domination None",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_sorted_domination None",
        "grasp grasp 2 5 300 100 stochastically None after_local",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_random after_local",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_sorted_score after_local",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_sorted_score_r after_local",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_random_domination after_local",
        "grasp grasp 2 5 300 100 stochastically best_first_neighbor_sorted_domination after_local",

        "grasp grasp s1 5 300 100 uniform None None",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_random None",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_sorted_score None",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_sorted_score_r None",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_random_domination None",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_sorted_domination None",
        "grasp grasp s1 5 300 100 uniform None after_local",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_random after_local",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_sorted_score after_local",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_sorted_score_r after_local",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_random_domination after_local",
        "grasp grasp s1 5 300 100 uniform best_first_neighbor_sorted_domination after_local",
        "grasp grasp s1 5 300 100 stochastically None None",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_random None",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_sorted_score None",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_sorted_score_r None",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_random_domination None",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_sorted_domination None",
        "grasp grasp s1 5 300 100 stochastically None after_local",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_random after_local",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_sorted_score after_local",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_sorted_score_r after_local",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_random_domination after_local",
        "grasp grasp s1 5 300 100 stochastically best_first_neighbor_sorted_domination after_local",

        "grasp grasp s2 5 300 100 uniform None None",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_random None",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_sorted_score None",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_sorted_score_r None",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_random_domination None",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_sorted_domination None",
        "grasp grasp s2 5 300 100 uniform None after_local",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_random after_local",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_sorted_score after_local",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_sorted_score_r after_local",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_random_domination after_local",
        "grasp grasp s2 5 300 100 uniform best_first_neighbor_sorted_domination after_local",
        "grasp grasp s2 5 300 100 stochastically None None",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_random None",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_sorted_score None",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_sorted_score_r None",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_random_domination None",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_sorted_domination None",
        "grasp grasp s2 5 300 100 stochastically None after_local",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_random after_local",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_sorted_score after_local",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_sorted_score_r after_local",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_random_domination after_local",
        "grasp grasp s2 5 300 100 stochastically best_first_neighbor_sorted_domination after_local",

        "grasp grasp s3 5 300 100 uniform None None",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_random None",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_sorted_score None",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_sorted_score_r None",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_random_domination None",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_sorted_domination None",
        "grasp grasp s3 5 300 100 uniform None after_local",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_random after_local",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_sorted_score after_local",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_sorted_score_r after_local",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_random_domination after_local",
        "grasp grasp s3 5 300 100 uniform best_first_neighbor_sorted_domination after_local",
        "grasp grasp s3 5 300 100 stochastically None None",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_random None",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_sorted_score None",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_sorted_score_r None",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_random_domination None",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_sorted_domination None",
        "grasp grasp s3 5 300 100 stochastically None after_local",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_random after_local",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_sorted_score after_local",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_sorted_score_r after_local",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_random_domination after_local",
        "grasp grasp s3 5 300 100 stochastically best_first_neighbor_sorted_domination after_local",

        "genetic geneticnds 1 5 20 100 tournament 2 onepoint 0.8 flip1bit 0.1 elitism",

    ]

    #grasps = generate_configurations()

    #genetics = 
    for alg in algorithms:
        f.write(alg+ '\n')

    f.close()


generate_configurations()
